name: witc
version: 0.3.1.0
github: "second-state/witc"
license: Apache-2.0
author: "secondstate"
maintainer:
  - "dannypsnl@secondstate.io"
  - "dm4@users.noreply.github.com"
copyright: "2023 secondstate"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/second-state/witc#readme>

dependencies:
  - base >= 4.7 && < 5
  - mtl >= 2.2
  - containers >= 0.6
  - transformers >= 0.5
  - primitive >= 0.7
  - directory >= 1.3
  - megaparsec >= 9.2
  - text >= 1.2
  - prettyprinter >= 1.7
  - prettyprinter-ansi-terminal >= 1.1.3
  - template-haskell >= 2.18
  - optparse-applicative >= 0.16
  - filepath >= 1.4

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - FlexibleContexts
  - ImportQualifiedPost
  - DuplicateRecordFields
  - OverloadedRecordDot
  - LambdaCase
  - ViewPatterns

library:
  source-dirs: src

executables:
  witc:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - witc

tests:
  witc-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - witc
      - hspec
      - hspec-megaparsec
