name: Run examples

on:
  push:
    branches:
      - main
    paths:
      - "**.hs"
      - "**.cabal"
      - "**.yaml"
      - "**.yml"
      - "**.toml"
      - "**.rs"
      - "**.wit"
  pull_request:
    branches:
      - main
    paths:
      - "**.hs"
      - "**.cabal"
      - "**.yaml"
      - "**.yml"
      - "**.toml"
      - "**.rs"
      - "**.wit"

jobs:
  cargo_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
      - uses: actions-rs/toolchain@v1
        with:
          default: true
          toolchain: nightly-2022-11-02-x86_64-unknown-linux-gnu
          target: wasm32-wasi
      - name: Install WasmEdge
        run: |
          curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash
      - name: Install witc
        run: |
          stack install
      - name: Run example/WitTest
        run: |
          source $HOME/.wasmedge/env
          cd example/WitTest
          cargo run --release
