name: Integration Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    name: Run Rust test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: wasm32-wasi
      - name: Install WasmEdge
        run: |
          curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.13.3
      - name: Install witc
        run: |
          stack install
      - name: Run tess
        run: |
          source $HOME/.wasmedge/env
          cd test-project && make test
