name: Release witc artifacts

on:
  # Trigger the workflow on the new 'v*' tag created
  push:
    tags: ["v*"]

jobs:
  create_release:
    name: Create Github Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: "9.2.8"
      - run: stack install

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: witc
          path: "${{ env.HOME }}/.local/bin/witc"

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: witc
